dist: xenial
language: bash

branches:
  only:
    - master

env:
  - tf_version=0.12.28 tf_init_cli_options="-input=false" tf_validation_cli_options=""

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

jobs:
  include:
    - stage: terraform plan
      script:
        - echo "Mocking terraform service key..."
        - mkdir -p ./.keys
        - echo "{}" > ./.keys/terraform.json
        - echo "validating terraform"
        - terraform fmt -recursive -check
        - terraform init $tf_init_cli_options
        - terraform validate $tf_validation_cli_options
